// <auto-generated />
using EmployeeTracking.Data.Concrete.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeTracking.Data.Migrations
{
    [DbContext(typeof(EmployeeTrackingContext))]
    [Migration("20230501191308_EmployeeDb")]
    partial class EmployeeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EmployeeTracking.Entity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yazılım"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Muhasebe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "İnsan Kaynakları"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İhracat"
                        });
                });

            modelBuilder.Entity("EmployeeTracking.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("salary")
                        .HasMaxLength(300)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Büşra",
                            LastName = "Dursun",
                            salary = 30000
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 4,
                            FirstName = "Erdinç",
                            LastName = "Dursun",
                            salary = 20000
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            FirstName = "Ömer",
                            LastName = "Dursun",
                            salary = 5000
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            FirstName = "Zeynep",
                            LastName = "Doğan",
                            salary = 15000
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            FirstName = "Ayşe",
                            LastName = "Doğan",
                            salary = 28000
                        });
                });

            modelBuilder.Entity("EmployeeTracking.Entity.Employee", b =>
                {
                    b.HasOne("EmployeeTracking.Entity.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
