// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YogaApp.Data.Concrete.EfCore.Contexts;

#nullable disable

namespace YogaApp.Data.Migrations
{
    [DbContext(typeof(YogaAppContext))]
    [Migration("20230703192521_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("YogaApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5496),
                            Description = "Hatha yoga ismini Sanskritçe’de güneş ve ay anlamına gelen kelimelerden alır. Karşıt güçleri dengelemek için uygulanır. Bu yoga türünde denge, güç ve esneklikten, fiziksel ve zihinsel enerjiden veya nefes ve bedenden gelebilir. Hatha farklı stiller ve okullar için kapsayıcı bir kavramdır. Yani tüm yoga fiziksel hareketlerini kapsayan bir yoga türüdür. Fiziksel uygulamaya dayanan diğer ashtanga, iyengar gibi yoga stillerini içerir. Ancak fiziksel temelli kriya, raja ve karma yogadan ayrışır. Hatha, ‘güç’ anlamına gelir. Ancak bu güçlülük, vücuda daha fazla yüklenmek anlamına gelmez. Daha çok konsantrasyon ve uygulamaya işaret eder. Daha dengeli ve nazik hareketler içeren bir yogadır. Vücutta enerji noktalarının yoğunlaştığı ve 7 noktada yer alan çakra ve enerji noktaları arasındaki uyum üzerine çalışır. Araştırmalar, hatha yoga, stresin azaltılması, fiziksel olarak zindelik hissi ve daha genç bir görünüme sahip olmasını destekler. Sürekli yapıldığı takdirde kilo kaybına ve sıkı kaslara kavuşulmasını sağlar.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5517),
                            Name = "Hatha Yoga",
                            Url = "hatha-yoga"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5523),
                            Description = "Ashtanga yoga daha çok kilo kaybı için uygulanan bir yoga türüdür. Sanskritçe ‘sekiz’ kelimesinden türetilmiştir. Ashtanga yoganın 8 ayağı vardır. Bu ayaklar; ilkeler, kişisel disiplin, asana ve duruşlar, pranayama, geri çekilme, konsantrasyon, meditasyon ve kurtuluştur. Vinyasa yoga ile bazı unsurları taşır",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5524),
                            Name = "Ashtanga Yoga",
                            Url = "ashtanga-yoga"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5527),
                            Description = "Vinyasa yoga bir tür akış yogası olarak da adlandırılır. Vinyasa kelime olarak Vi (vasyasyon) ve nyasa (öngörülen sınırlar) kelimelerinin birleştirilmesiyle oluşturulmuştur. Vinyasa yoga da hareket ve nefes alma tekniklerini birleştirir. Kontrollü nefes alma ile birlikte bir duruş akışı yaratır. Örneğin; akış bir çocuğun duruşu ile başlatılır ve savasana denen ölüm duruşuyla sonlandırılır. Her duruştaki geçişler ise yaşam boyunca süren hareketi temsil eder. Meditasyon ise ileri seviye vinyasa yoganın bir parçasıdır. Aerobik egzersiz gibi kalbe iyi gelir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5528),
                            Name = "Vinyasa Yoga",
                            Url = "vinyasa-yoga"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5530),
                            Description = "Iyengar yoga Bellur Krishnamachar Sundararaja Iyengar tarafından bulunmuş bir yoga türüdür. Hizalama, ayrıntılı ve hassas hareketlere odaklanırken nefes çeşitli duruşlarla kontrol edilir. Bu yoga türü vinyasa yogaya benzerdir. Duruş, vücut hizalaması ve vücudun açılması bu yoganın önceliğidir. Kusursuz duruşlar için yoga blokları ve kemerler kullanılabilir. ",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5531),
                            Name = "Iyengar Yoga",
                            Url = "iyengar-yoga"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5533),
                            Description = "Yin yoga, yoga ve dövüş sanatlarının karışımı olan bir yoga türüdür. Bu yoga ile eklemlerdeki kan dolaşımı artar, esneklik ve kas yoğunluğu gelişir. Yin yoga uzun süreli oturma duruşları içerir ve yavaş tempoludur. Dinginlik ve iç huzur için genellikle bu yoga türü tercih edilir. Kaliteli bir uyku için de yapılır.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5534),
                            Name = "Yin Yoga",
                            Url = "yin-yoga"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5536),
                            Description = "Farkındalık yogası olarak da bilinen bu yoga türü, tekrarlayan pozisyonları içerir. Omurganın alt kısmında sıkışık şekilde bulunan spritüel Kundalini enerjisinin, yukarı doğru hareket ederek serbest kaldığı, böylece ruhsal iyileşmeye destek verdiğine inanılır. Bu nedenle de stres, kaygı, depresyon ve daha iyi bilişsel işlevler için iyi olduğu söylenir. Ruhsal ve fiziksel olarak eşit bir bütünlük sunar. ",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5537),
                            Name = "Kundalini Yoga",
                            Url = "kundalini-yoga"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5539),
                            Description = "Çeşitli duruşlarla rahatlama sağlamayı amaçlayan restoratif yogada vücuda destek sağlamak için aksesuarlar kullanılır. Rehber eşliğindeki meditasyon bu yoganın vazgeçilmez bir parçasıdır. Sinir sisteminin gevşemesini sağlayan bu yoga, sakinleşmek için tercih edilir. Uzun günün ardından özellikle dinlenmek için yapılan restoratif yoga, zihnin özgürleşmesine de yardımcı olur.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(5539),
                            Name = "Restoratif Yoga",
                            Url = "restoratif-yoga"
                        });
                });

            modelBuilder.Entity("YogaApp.Entity.Concrete.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 29,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9239),
                            FirstName = "Büşra",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Öztürk",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9242),
                            PhotoUrl = "busra-ozturk.jpeg",
                            Price = 500m,
                            Url = "busra-ozturk"
                        },
                        new
                        {
                            Id = 2,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.  ",
                            Age = 19,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9255),
                            FirstName = "Nazlı",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Öztürk",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9256),
                            PhotoUrl = "nazli-ozturk.jpeg",
                            Price = 300m,
                            Url = "nazli-ozturk"
                        },
                        new
                        {
                            Id = 3,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 35,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9262),
                            FirstName = "Arzu",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Topaloglu",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9262),
                            PhotoUrl = "busra-ozturk.jpeg",
                            Price = 450m,
                            Url = "arzu-topaloglu"
                        },
                        new
                        {
                            Id = 4,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9267),
                            FirstName = "Ayşe",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Doğan",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9267),
                            PhotoUrl = "ayse-dogan.jpeg",
                            Price = 800m,
                            Url = "ayse-dogan"
                        },
                        new
                        {
                            Id = 5,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 27,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9272),
                            FirstName = "Zeynep",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dursun",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9273),
                            PhotoUrl = "zeynep-dursun.jpeg",
                            Price = 575m,
                            Url = "zeynep-dursun"
                        },
                        new
                        {
                            Id = 6,
                            About = " Hakkında kısmı",
                            Age = 32,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9277),
                            FirstName = "Ülkü",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Boz",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9278),
                            PhotoUrl = "ulku-boz.jpeg",
                            Price = 280m,
                            Url = "ulku-boz"
                        },
                        new
                        {
                            Id = 7,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 28,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9282),
                            FirstName = "Betül",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Çalık",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9283),
                            PhotoUrl = "betul-calik.jpeg",
                            Price = 760m,
                            Url = "betul-calik"
                        },
                        new
                        {
                            Id = 8,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 29,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9287),
                            FirstName = "Erdinc",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dursun",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9288),
                            PhotoUrl = "erdinc-dursun.jpeg",
                            Price = 500m,
                            Url = "erdinc-dursun"
                        },
                        new
                        {
                            Id = 9,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 42,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9370),
                            FirstName = "Ceren",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Özkök",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9372),
                            PhotoUrl = "ceren-ozkok.jpeg",
                            Price = 800m,
                            Url = "ceren-ozkok"
                        },
                        new
                        {
                            Id = 10,
                            About = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Age = 25,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9377),
                            FirstName = "Zehra",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            ModifiedDate = new DateTime(2023, 7, 3, 22, 25, 21, 840, DateTimeKind.Local).AddTicks(9378),
                            PhotoUrl = "zehra-yilmaz.jpeg",
                            Price = 300m,
                            Url = "zehra-yilmaz"
                        });
                });

            modelBuilder.Entity("YogaApp.Entity.Concrete.Instructor", b =>
                {
                    b.HasOne("YogaApp.Entity.Concrete.Category", "Category")
                        .WithMany("Instructors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YogaApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("Instructors");
                });
#pragma warning restore 612, 618
        }
    }
}
